@FLP.AzureFunctions_HostAddress = http://localhost:7110

### Get Function1

GET {{FLP.AzureFunctions_HostAddress}}/api/Function1

### Create Bug Function

POST {{FLP.AzureFunctions_HostAddress}}/api/CreateBugFunction
{
    "title": "Sample Bug",
    "description": "This is a sample bug description.",
    "severity": "High",

}

###
