@FLP.AzureFunctions_HostAddress = http://localhost:7110
@data = {{}}
### Create Bug Function
# @name CreateBugFunction
POST {{FLP.AzureFunctions_HostAddress}}/api/Bug
content-type: application/json
{
    "Title": "Sample Bug",
    "Description": "This is a sample bug description.",
    "Severity": "High",

}
### Get Bug By Id
# $name GetBugByIdFunction
GET {{FLP.AzureFunctions_HostAddress}}/api/Bug/{{CreateBugFunction.response.body.$.data.id}}

### Get paginated Bug
# $name GetPaginatedBugFunction
GET {{FLP.AzureFunctions_HostAddress}}/api/Bug?page=1&pagesize=10

### Update Bug Function
# @name UpdateBugFunction
PUT {{FLP.AzureFunctions_HostAddress}}/api/Bug
content-type: application/json
{
    "Id": "{{CreateBugFunction.response.body.$.data.id}}",
    "Title": "Sample Updated Bug",
    "Description": "This is a sample Updated bug description.",
    "Severity": "High",
    "Status" : "Open",
    "AssignedToUserId": "{{$guid}}",
}
### Delete Bug Function
# @name DeleteBugFunction
DELETE {{FLP.AzureFunctions_HostAddress}}/api/Bug/{{CreateBugFunction.response.body.$.data.id}}
